### PR TITLE
Fix case sensitive search

### LINKED ISSUE #100: fix case sensitive in search
fix case sensitive in search

### PR DESCRIPTION
**Pull request by Israa91**
Relates #100 
- Make the search case in sensitive 
- fetch all workspaces , then filter according to user input

### CODE REVIEW

**Review by alaa-sahloub — DISMISSED** [review]

File: src/firebase/firestore/workspace/fetchSearchResults.js [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+      );
+      return result;
+    }
+    if (q) {
+      const result = allData.filter(
+        (ws) => ws.name.toLowerCase() === q.toLowerCase()
+      );
+      return result;
+    }
+    if (city) {
```
Comment (lina-jamal) [inline src/firebase/firestore/workspace/fetchSearchResults.js:57]: refactor the code,
make general function for filter

**Review by Sondos-Alalami — APPROVED** [review]

**Review by lina-jamal — APPROVED** [review]

**Review by alaa-sahloub — APPROVED** [review]
